### ISSUE TITLE
What this should be and how it should work?

### ISSUE THREAD

**Issue by gabrielfgularte** [gabrielfgularte/QRSocial#3]
I think QRSocial should be a webapp. So I'll try to describe what I think that could be a step-to-step user workflow.

**If I'm a blogger:**

1. Access QRSocial website
2. Login with Facebook or Twitter
3. Add all my profile urls on social networks 
4. Get an QRCode as image
5. Place that image on my YouTube videos description, Twitter and Facebook posts, etc

**If I'm a follower:**

1. Scan the QRCode posted by my favorite blogger
2. The QRCode redirects me to QRSocial website
3. I choose the social networks that I'd like to follow my favorite blogger
4. For each social network I've selected, I have to connect and accept to follow that blogger

Have I missed something?
I've made a mistake about some step?
This is the better approach to this tool?

What you say?

**Comment by gabrielfgularte** [comment]
If QRSocial will be a webapp, what technologies we'll use to develop it?

**Comment by barbier** [comment]
I don't know how to create a QRCode, but maybe Node or Python?

**Comment by gabrielfgularte** [comment]
I've found these two libs:
JS: https://davidshimjs.github.io/qrcodejs/
Python: https://pypi.python.org/pypi/qrcode

**Comment by gabrielfgularte** [comment]
@barbier I'm gonna move this into the #2, ok?
